CREATE TABLE tbl_user (
  user_id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
  email VARCHAR(255) NOT NULL UNIQUE, 
  first_name VARCHAR(255) NOT NULL, 
  last_name VARCHAR(255) NOT NULL, 
  PRIMARY KEY(user_id)
);